language: python

python:
    - "2.7"

env:
    - DB=mysql

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install build-essential python-pip python-virtualenv python-imaging libxml2-dev libjpeg62-dev python-jinja2 python-bcrypt python-mysqldb
    - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libfreetype.so /usr/lib
    - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libz.so /usr/lib
    - cp badgus/settings/local.py-travis badgus/settings/local.py
    - mysql -e 'create database badgus;'

install:
    - scripts/peep.py install -r requirements/compiled.txt -r requirements/dev.txt

script: python manage.py test -v2

notifications:
    email:
        - me@lmorchard.com
